name: Update Job Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Create jobs-data.json
        run: |
          echo "Creating jobs-data.json..."
          cat > jobs-data.json << 'EOF'
          {
            "jobs": [
              {
                "id": "job-$(date +%s)-1",
                "title": "Safeguarding Officer",
                "organization": "AADA",
                "location": "Kabul",
                "type": "Full Time",
                "category": "Health Care",
                "postedDate": "$(date -u +"%Y-%m-%d")",
                "deadline": "2025-09-05",
                "source": "acbar.org",
                "sourceUrl": "https://www.acbar.org/jobs/",
                "description": "Position available for Safeguarding Officer. Visit the website for details.",
                "requirements": []
              },
              {
                "id": "job-$(date +%s)-2",
                "title": "Senior Accountant",
                "organization": "UNICEF",
                "location": "Kabul",
                "type": "Contract",
                "category": "Finance",
                "postedDate": "$(date -u +"%Y-%m-%d")",
                "deadline": "2025-09-10",
                "source": "jobs.af",
                "sourceUrl": "https://www.jobs.af/",
                "description": "Senior Accountant position available. Visit the website for details.",
                "requirements": []
              }
            ],
            "lastUpdated": "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")",
            "totalCount": 2,
            "sources": {
              "acbar": 1,
              "jobsaf": 1
            },
            "warning": "This is mock data. In a production system, this would be replaced with real scraped data."
          }
          EOF
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add jobs-data.json
          git commit -m "Update job data $(date)" || echo "No changes to commit"
          git push
