    - name: Ensure jobs-data.json exists
      run: |
        if [ ! -f "jobs-data.json" ]; then
          echo "Creating initial jobs-data.json..."
          cat > jobs-data.json << 'EOF'
{
  "jobs": [],
  "lastUpdated": "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")",
  "totalCount": 0,
  "sources": {
    "acbar": 0,
    "jobsaf": 0
  },
  "warning": "This file will be automatically updated by the scraper. Initial file created manually."
}
EOF
        fi
