name: Update Job Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Create jobs-data.json
        run: |
          node -e "
          const fs = require('fs');
          const mockJobs = [
            {
              id: 'acbar-' + Date.now() + '-1',
              title: 'Safeguarding Officer',
              organization: 'AADA',
              location: 'Kabul',
              type: 'Full Time',
              category: 'Health Care',
              postedDate: new Date().toISOString().split('T')[0],
              deadline: '2025-09-05',
              source: 'acbar.org',
              sourceUrl: 'https://www.acbar.org/jobs/123',
              description: 'Organize and implement continuous training on child protection and gender-based violence for all staff and partners.',
              requirements: ['Experience in safeguarding', 'Knowledge of child protection standards']
            },
            {
              id: 'jobsaf-' + Date.now() + '-2',
              title: 'Senior Accountant',
              organization: 'UNICEF',
              location: 'Kabul',
              type: 'Contract',
              category: 'Finance',
              postedDate: new Date().toISOString().split('T')[0],
              deadline: '2025-09-10',
              source: 'jobs.af',
              sourceUrl: 'https://www.jobs.af/job/456',
              description: 'Oversee financial operations and ensure compliance with international accounting standards.',
              requirements: ['Professional accounting qualification', 'Experience with ERP systems']
            }
          ];
          
          const jobsData = {
            jobs: mockJobs,
            lastUpdated: new Date().toISOString(),
            totalCount: mockJobs.length,
            sources: {
              acbar: 1,
              jobsaf: 1
            },
            warning: 'This is mock data. In a production system, this would be replaced with real scraped data.'
          };
          
          fs.writeFileSync('jobs-data.json', JSON.stringify(jobsData, null, 2));
          console.log('Successfully created jobs-data.json');
          "
      
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add jobs-data.json
          git commit -m "Update job data $(date)" || echo "No changes to commit"
          git push
